version: '3.8'

services:
  retgen-api:
    build: .
    container_name: retgen-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      # Optional: Load pre-trained model on startup
      # - RETGEN_MODEL_PATH=/models/pretrained
    volumes:
      # Mount model directory for persistence
      - ./models:/app/models
      # Mount for development (optional)
      # - ./src:/app/src
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: retgen-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - retgen-api
    restart: unless-stopped

  # Optional: Redis for caching
  redis:
    image: redis:alpine
    container_name: retgen-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: